Repository MarquezProject/marquez-python, pull requests merged in 2019-05, with the labels that each got.

#39 Remove travis.yml
  .travis.yml
Labels: review

#42 Feature/add getting started info to readme
  README.md
Labels: review

#44 Update the install instructions in the README
  README.md
Labels: review

#38 Wip/class rename
  .circleci/config.yml
  README.md
  marquez_client/__init__.py
  marquez_client/client.py
  tests/integration/integration_test.py
  tests/test_configuration.py
  tests/test_datasets.py
  tests/test_datasources.py
  tests/test_jobruns.py
  tests/test_jobs.py
  tests/test_namespaces.py
Labels: WIP

#49 Bump marquez image used in integration tests
  tests/integration/docker-compose.yml
Labels: review

#48 Make job_run_args param in create_job_run() optional
  marquez_client/client.py
Labels: review

#60 Add optional field checks in payload
  marquez_client/client.py
Labels: bug
